/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;
    
import Frontera.FramePrincipal;
/**
 *
 * @author 192545681742
 */
public class GestionDeProductos extends javax.swing.JPanel {
    
    private AnadirProducto anadirP = new AnadirProducto();
    private QuitarProducto quitarP = new QuitarProducto();
    private AnadirExistencias anadirE = new AnadirExistencias();
    private QuitarExistencia quitarE = new QuitarExistencia();
    private EditarProducto editarP= new EditarProducto();
    private ConsultarIni consultarP= new ConsultarIni();
    private FramePrincipal fp = new FramePrincipal();
    
    /**
     * Creates new form GestionDeProductos
     */
    public GestionDeProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnadirP = new javax.swing.JButton();
        QuitarP = new javax.swing.JButton();
        EditarP = new javax.swing.JButton();
        AnadirE = new javax.swing.JButton();
        QuitarE = new javax.swing.JButton();
        ConsultarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        AnadirP.setText("Añadir Producto");
        AnadirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirPActionPerformed(evt);
            }
        });

        QuitarP.setText("Quitar Producto");
        QuitarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarPActionPerformed(evt);
            }
        });

        EditarP.setText("Editar Producto");
        EditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPActionPerformed(evt);
            }
        });

        AnadirE.setText("Añadir Existencias");
        AnadirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirEActionPerformed(evt);
            }
        });

        QuitarE.setText("Quitar Existencias");
        QuitarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarEActionPerformed(evt);
            }
        });

        ConsultarP.setText("Consultar Producto");
        ConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPActionPerformed(evt);
            }
        });

        jLabel1.setText("    Gestión de productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AnadirE, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuitarE, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsultarP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AnadirP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuitarP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnadirP)
                    .addComponent(QuitarP)
                    .addComponent(EditarP))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnadirE)
                    .addComponent(QuitarE)
                    .addComponent(ConsultarP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void QuitarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarPActionPerformed
        fp.getjButton1().
        panelPrincipal.removeAll();
        panelPrincipal.add(quitarP);
        panelPrincipal.setVisible(true);
    }//GEN-LAST:event_QuitarPActionPerformed

    private void AnadirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnadirEActionPerformed

    private void AnadirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnadirPActionPerformed

    private void EditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPActionPerformed

    private void QuitarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitarEActionPerformed

    private void ConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirE;
    private javax.swing.JButton AnadirP;
    private javax.swing.JButton ConsultarP;
    private javax.swing.JButton EditarP;
    private javax.swing.JButton QuitarE;
    private javax.swing.JButton QuitarP;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
